### PR TITLE
Versionlock plugin

### PR DESCRIPTION
**Pull request by MichaelMraka**

### CODE REVIEW

**Comment by gvegidy** [comment]
Hi Michael,

thanks for stepping up and implementing this plugin. I did some short tests by installing a clean F22 and patch the dnf-plugins-extras package with your code:

Locking packages works as expected, even with package dependencies, reinstalls and everything. Very good.

But "dnf versionlock clear" does not work at all, all locks stay in place.

Also adding a lock sometimes does strange things: consider package "foo" of which we have version 1.1-1 installed, but some repos also offer 1.0-1 and 2.0-1. When you now call "dnf versionlock add foo" you get:

Adding versionlock on: foo-0:1.1-1.*
Adding versionlock on: foo-0:1.0-1.*
Adding versionlock on: foo-0:2.0-1.*

And there is something else I'd also improve: when you call "dnf versionlock add packagethatisnotinstalled", you get exactly zero output (except the metadata expiration info you always get). I suggest to give some warning message to the user.

**Comment by MichaelMraka** [comment]
Hello, this is a fix for clear command and improvements to the add command.
Please give it a try, thanks.

**Comment by gvegidy** [comment]
Hi Michael,

thanks for fixing this so fast. I can confirm that all 3 issues from my last message are fixed with your latest patches.

I was now playing with package epochs and found this: I installed foo-0:1.1-1 (epoch 0) and added a versionlock for it. Then I build foo-1:1.1-1 (epoch 1), put it in my repo and ran dnf update. It now wanted to update foo. I'd say it should not. Sorry for not reporting this in my first review, but the idea to test this just came to me this evening.

**Comment by MichaelMraka** [comment]
Hi,
What string was exactly added to the versionlock.list file? Was it foo-0:1.1-1 or foo-1.1-1?
If it's the first case I'm afraid it's a bug in dnf (either in package spec parsing or in add_exclude()).

**Comment by MichaelMraka** [comment]
According to my investigation it's a bug in dnf. See https://bugzilla.redhat.com/show_bug.cgi?id=1229730.

**Comment by gvegidy** [comment]
Thank you for implementig this and taking care of the epoch bugreport.

**Pull request merged**
