### PR TITLE
Spec changes - removed python2-dnf-plugin-system-upgrade build

### PR DESCRIPTION
**Pull request by j-mracek**

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
somehow I miss the point why python2 version will not work =(

**Comment by j-mracek** [comment]
@ignatenkobrain It always call python3 (dnf-3) during the reboot, therefore it will always fail in case of absence of python-3 plugin.

**Comment by Conan-Kudo** [comment]
@j-mracek Why is it always doing that?

**Comment by j-mracek** [comment]
@Conan-Kudo On Fedora 23+ if you run ``dnf``` you are redirected to ``dnf-3``. If you have only python2-dnf-plugin-system-upgrade (and not python3 version) you run easily "dnf-2 system-upgrade download" and then "dnf-2 system-upgrade reboot", but during reboot systemD call "dnf system-upgrade upgrade" therefore it results in "It could be a DNF plugin command, try: "dnf install 'dnf-command(system-upgrade)'"". And from my side, there is no need of that plugin for python2, because there is no way how to have fedora 23+ without python3 version.

**Comment by Conan-Kudo** [comment]
So the actual problem is that we provide both `dnf-2` and `dnf-3` and don't provide a way for the system-upgrade plugin to know which one to use.

**Comment by Conan-Kudo** [comment]
@j-mracek Then what you should do is ship only one version, depending on which dnf is default.

**Comment by m-blaha** [comment]
@j-mracek please rebase, if this PR is still relevant

**Comment by j-mracek** [comment]
The issue will be solved by fedore30 anyway

**Pull request closed without merging**
