### PR TITLE
Change name of function calls according to dnf

### PR DESCRIPTION
**Pull request by j-mracek**
Required by rpm-software-management/dnf#540

### CODE REVIEW

**Comment by j-mracek** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;NvaeJDxC&#x2F;444-make-dnf-non-api-methods-private"> make DNF non-API methods private</a>

**Comment by jsilhan** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;mvRwfyIw&#x2F;351-dnf-2-0"> DNF 2.0</a>

**Comment by ignatenkobrain** [comment]
@jsilhan @j-mracek stop pushing private links in public repo!

**Comment by j-mracek** [comment]
@ignatenkobrain The links are added by Trello - Advanced functions

**Comment by ignatenkobrain** [comment]
@j-mracek I don't care how they are added, but I don't want to see private links in public repository.

**Comment by j-mracek** [comment]
@mluscon Please can you review also this PR. It is part of privatization that you already merged. Thanks a lot.

**Comment by j-mracek** [comment]
Please merge it - this is last privatization PR that is still unmerged.

**Pull request merged**
