### PR TITLE
Feature Request: implement unattended mode config option

### PR DESCRIPTION
**Pull request by mstefany**
I have recently contributed "unattended mode" of operation to rpmconf, now it would nice if dnf-plugin-rpmconf would support it.

https://github.com/xsuchy/rpmconf/pull/45

### CODE REVIEW

**Comment by m-blaha** [comment]
Hi, thanks for the patch!
The patch introduces new configuration option `unatended` for rpmconf plugin. This option needs to be documented in doc/rpmconf.rst file.

**Comment by mstefany** [comment]
My bad, I have added a short section to `doc/rpmconf.rst` about it - is it enough or should it be more detailed?

**Comment by m-blaha** [comment]
Thanks for the documentation!
Sorry, we have another problem I didn't notice at first - the required rpmconf-1.1.3 with `unattended` option implemented is not available for Fedora 32 and 33. The problem is that we are using the same `master` branch of dnf-plugins-core for releasing into all supported Fedora versions.

We must either

- postpone merging the patch until all supported Fedoras have the option available (could be speeded up by releasing proper version of rpmconf into F33 / F32)
- or make make the usage conditional (only if underlying rpmconf version supports `unattended`)

Otherwise the plugin would cause each dnf command to fail with something like:
```
# dnf install acpi
------------------- 8< -----------------
New leaves:
  acpi.x86_64
Traceback (most recent call last):
  File "/home/mblaha/src/dnf/dnf/plugin.py", line 104, in _caller
    getattr(plugin, method)()
  File "/home/mblaha/src/venv-3.8/lib/python3.8/site-packages/dnf-plugins/rpm_conf.py", line 82, in transaction
    rconf = rpmconf.RpmConf(
TypeError: __init__() got an unexpected keyword argument 'unattended'
------------------- 8< -----------------
```

**Comment by mstefany** [comment]
Sorry for a later reply. We are using rpmconf and dnf-plugins-extras on CentOS 8. I checked that rpmconf 1.1.3 is already available in EPEL 8, but as you say, not in Fedora 32 or 33, it's only in Rawhide. dnf-plugins-extras in not available on CentOS at all, not even on EPEL, so we are still dependent on our own builds of such packages. So if you merge this only later on when rpmconf 1.1.3 is available in Fedora I am pretty OK with that. It would be nice is these tools become part of the core software in RHEL/CentOS 9. Thank you.

**Comment by emansom** [comment]
Status on this? Would love it to never have to worry about cleaning up `.rpmsave` and `.rpmnew` on my servers again. 😄

**Comment by m-blaha** [comment]
Appologies for late response, the PR somehow got forgotten... I'm merging it now.

**Pull request merged**
