### PR TITLE
Redirect logger.info into stderr for repomanage (RhBug:1377742)

### PR DESCRIPTION
**Pull request by j-mracek**
Requires: https://github.com/rpm-software-management/dnf/pull/681

### CODE REVIEW

**Comment by MichaelMraka** [comment]
retest

**Comment by MichaelMraka** [comment]
Failed tests (rpmbuild):

+ PYTHONPATH=/builddir/build/BUILDROOT/dnf-plugins-extras-0.10.0_rc1-9g0b54e53.fc24.x86_64/usr/lib/python2.7/site-packages:/builddir/build/BUILDROOT/dnf-plugins-extras-0.10.0_rc1-9g0b54e53.fc24.x86_64/usr/lib/python2.7/site-packages/dnf-plugins/
+ nosetests-2.7 -s tests/
/usr/lib64/python2.7/optparse.py:1013: PendingDeprecationWarning: The KSOption class is deprecated and will be removed in pykickstart-3.  Use the argparse module instead.
  option = self.option_class(*args, **kwargs)
....usage: dnf kickstart [-c [config file]] [-q] [-v] [--version]
                     [--installroot [path]] [--noplugins]
                     [--disableplugins [plugin]] [--releasever RELEASEVER]
                     [--setopt SETOPTS] [--skip-broken] [-h] [--allowerasing]
                     [-b] [-C] [-d [debug level]] [--debugsolver]
                     [--showduplicates] [-e ERRORLEVEL]
                     [--rpmverbosity [debug level name]] [-y] [--assumeno]
                     [--enablerepo [repo]] [--disablerepo [repo] | --repo
                     [repo]] [-x [package]] [--disableexcludes [repo]]
                     [--repofrompath [repo,path]] [--nogpgcheck]
                     [--color COLOR] [--refresh] [-4] [-6] [--downloadonly]
                     [--bugfix] [--enhancement] [--newpackage] [--security]
                     [--advisory ADVISORY] [--bzs BUGZILLA] [--cves CVES]
                     [--sec-severity {Critical,Important,Moderate,Low}]
                     filename
dnf kickstart: error: unrecognized arguments: path2.ks
..............EEEESSSS.......S.............................
======================================================================
ERROR: test_keep_option (tests.test_repomanage.TestRepoManageFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/dnf-plugins-extras-0.10.0_rc1-9g0b54e53/tests/test_repomanage.py", line 63, in test_keep_option
    support.command_run(self.cmd, args)
  File "/builddir/build/BUILD/dnf-plugins-extras-0.10.0_rc1-9g0b54e53/tests/support.py", line 45, in command_run
    command_configure(cmd, args)
  File "/builddir/build/BUILD/dnf-plugins-extras-0.10.0_rc1-9g0b54e53/tests/support.py", line 42, in command_configure
    return cmd.configure()
  File "/builddir/build/BUILDROOT/dnf-plugins-extras-0.10.0_rc1-9g0b54e53.fc24.x86_64/usr/lib/python2.7/site-packages/dnf-plugins/repomanage.py", line 52, in configure
    self.cli.redirect_logger(stdout=logging.WARNING, stderr=logging.INFO)
AttributeError: 'CliStub' object has no attribute 'redirect_logger'
======================================================================
ERROR: test_new_option (tests.test_repomanage.TestRepoManageFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/dnf-plugins-extras-0.10.0_rc1-9g0b54e53/tests/test_repomanage.py", line 54, in test_new_option
    support.command_run(self.cmd, args)
  File "/builddir/build/BUILD/dnf-plugins-extras-0.10.0_rc1-9g0b54e53/tests/support.py", line 45, in command_run
    command_configure(cmd, args)
  File "/builddir/build/BUILD/dnf-plugins-extras-0.10.0_rc1-9g0b54e53/tests/support.py", line 42, in command_configure
    return cmd.configure()
  File "/builddir/build/BUILDROOT/dnf-plugins-extras-0.10.0_rc1-9g0b54e53.fc24.x86_64/usr/lib/python2.7/site-packages/dnf-plugins/repomanage.py", line 52, in configure
    self.cli.redirect_logger(stdout=logging.WARNING, stderr=logging.INFO)
AttributeError: 'CliStub' object has no attribute 'redirect_logger'
======================================================================
ERROR: test_old_option (tests.test_repomanage.TestRepoManageFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/dnf-plugins-extras-0.10.0_rc1-9g0b54e53/tests/test_repomanage.py", line 43, in test_old_option
    support.command_run(self.cmd, args)
  File "/builddir/build/BUILD/dnf-plugins-extras-0.10.0_rc1-9g0b54e53/tests/support.py", line 45, in command_run
    command_configure(cmd, args)
  File "/builddir/build/BUILD/dnf-plugins-extras-0.10.0_rc1-9g0b54e53/tests/support.py", line 42, in command_configure
    return cmd.configure()
  File "/builddir/build/BUILDROOT/dnf-plugins-extras-0.10.0_rc1-9g0b54e53.fc24.x86_64/usr/lib/python2.7/site-packages/dnf-plugins/repomanage.py", line 52, in configure
    self.cli.redirect_logger(stdout=logging.WARNING, stderr=logging.INFO)
AttributeError: 'CliStub' object has no attribute 'redirect_logger'
======================================================================
ERROR: test_space_option (tests.test_repomanage.TestRepoManageFunctions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/dnf-plugins-extras-0.10.0_rc1-9g0b54e53/tests/test_repomanage.py", line 74, in test_space_option
    support.command_run(self.cmd, args)
  File "/builddir/build/BUILD/dnf-plugins-extras-0.10.0_rc1-9g0b54e53/tests/support.py", line 45, in command_run
    command_configure(cmd, args)
  File "/builddir/build/BUILD/dnf-plugins-extras-0.10.0_rc1-9g0b54e53/tests/support.py", line 42, in command_configure
    return cmd.configure()
  File "/builddir/build/BUILDROOT/dnf-plugins-extras-0.10.0_rc1-9g0b54e53.fc24.x86_64/usr/lib/python2.7/site-packages/dnf-plugins/repomanage.py", line 52, in configure
    self.cli.redirect_logger(stdout=logging.WARNING, stderr=logging.INFO)
AttributeError: 'CliStub' object has no attribute 'redirect_logger'
----------------------------------------------------------------------
Ran 62 tests in 0.347s
FAILED (SKIP=5, errors=4)

**Comment by j-mracek** [comment]
tests this please

**Comment by j-mracek** [comment]
@MichaelMraka Fixed hopefully

**Comment by MichaelMraka** [comment]
@dnf-bot r+

**Pull request closed without merging**
