### PR TITLE
Reworked content of plugins in core and extras

### PR DESCRIPTION
**Pull request by j-mracek**
Requires: https://github.com/rpm-software-management/dnf-plugins-core/pull/199
Requires: https://github.com/rpm-software-management/ci-dnf-stack/pull/241

### CODE REVIEW

**Comment by MichaelMraka** [comment]
This is a big change in packaging so I'd like everybody to take a look.

**Comment by Conan-Kudo** [comment]
@j-mracek I'd rather that plugins that were in core stay there. That means the copr plugin should stay in dnf-plugins-core. That drastically simplifies this whole mess, too.

**Comment by j-mracek** [comment]
@jsilhan @ignatenkobrain @mhatina @jrohel Rebased, refactored, please take a second look.

**Comment by j-mracek** [comment]
@Conan-Kudo I removed requirement of copr plugin for fedora, therefore it will be little bit less messy. The reason why I removed copr plugin from Core is that we have to provide possibility to release dnf-plugins-core without copr plugin.

**Comment by Conan-Kudo** [comment]
@j-mracek You still haven't justified why you want to remove Copr plugin from core to begin with. The `yum-utils` argument is hollow, because there's no reason there can't be more plugins than what yum-utils bundled (and the yum plugin for copr was part of yum-utils anyway).

**Comment by j-mracek** [comment]
@Conan-Kudo At least I have to move it into separate package, like yum-utils, but anyway I would prefer this reorganization.

**Pull request merged**
