### PR TITLE
spec: adapt ot dnf 0.6.4-2 package split

### PR DESCRIPTION
**Pull request by jsilhan**

### CODE REVIEW

**Comment by jsilhan** [comment]
@rholy , can you test this too, please?
@ignatenkobrain , this should fix extras in rawhide - the bug you reported (https://github.com/rpm-software-management/dnf-plugins-core/pull/66). If this PR is ok, do the new extras build for f22 and f23, please.

**Comment by rholy** [comment]
Huh, sure, I can, but it will take me few days...

**Comment by jsilhan** [comment]
I thought that you have the script or do you do that manually?

**Comment by rholy** [comment]
Well, there are just dnf and dnf-plugins-core hardcoded there. So it will take several minutes to add extras but mainly the problem is the how long it takes to run the script.
Originally it tried to install all combinations of all the DNF packages on top of all combinations of all the DNF packages. So it was ```2048 × 2048``` tests. While the first 2048 tests took about 3 hours. Then I reduced the number of tested packages to 6, so it's now ```64 × 64``` tests. Adding the 19 dnf-plugins-extras packages it grows to ```33554432 × 33554432``` tests.

**Comment by jsilhan** [comment]
Can you test only last 2 dnf versions * installation of only one separate extras package  + dnf-plugins-extras package? Otherwise it would not finish in our century.

**Comment by ignatenkobrain** [comment]
Thanks!

**Pull request closed without merging**
