### PR TITLE
rename --repoid to --repo

### PR DESCRIPTION
**Pull request by MichaelMraka**
to make it consistent with --enablerepo/--disablerepo

### CODE REVIEW

**Comment by pnemade** [comment]
I am confused why we have this PR? I see yum repoquery already provide similar functionality for "--repoid switch". Why we want to rename this to "--repo"?

**Comment by MichaelMraka** [comment]
to make it consistent with --enablerepo/--disablerepo

**Comment by timlau** [comment]
It is a problem to change option of released tools, it can break peoples scipts. it is a API break, so the old one has to be depracated for a couple of releases before it is removed.
I would just add --repoid as an alias to --repo, so both option would work

parser.add_argument("--repo","--repoid", default=[], action="append",
                             help=_("Specify repositories to use"))

But I would not change it at all, for all other tools in dnf-plugins.core uses --repoid, so it would be very inconsistant if this tool uses -repo

**Comment by rholy** [comment]
Hm, is really a CLI change considered an API change?
Also, if we remove the switch just from the '--help' output, it's not a break of any interface.

**Comment by MichaelMraka** [comment]
All dnf tools has been fixed to use consistent naming which is repo. Moreover --repoid does still work (for compatibility reasons) but is hidden from help.

**Comment by timlau** [comment]
@rholy maybe not an API break, lacks a better word, there tools are used a lot in scripts, so removing options i bad, but as long as --repoid still work every thing should be ok

**Comment by ignatenkobrain** [comment]
merged. thanks!

**Pull request closed without merging**
