### PR TITLE
Check if pythonX-tracer is removed in transaction (RhBug:1379906)

### PR DESCRIPTION
**Pull request by j-mracek**
https://bugzilla.redhat.com/show_bug.cgi?id=1379906

Requires: https://github.com/rpm-software-management/dnf/pull/807

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
@j-mracek can we do something better instead? (in DNF)

Before running any plugins, find packages from system repo where **plugin file** belongs to and don't run that plugin if it is going to be removed.. This means we will solve all this problems. Because plugin has strict dependencies in packaging level, so if tracer is going to be removed, plugin will be removed as well.

**Comment by j-mracek** [comment]
@ignatenkobrain It sounds good, but there is a difficulty how to identify package that removes a dnf plugin (here glob in package name "*-dnf-plugin*" should work, but it is a glob), and then what plugin is provided by that package for disabling (here could help search in file provides, but that would be not a fun at all). Still don't see a good solution.

**Comment by ignatenkobrain** [comment]
@j-mracek DNF itself knows name of plugins and their paths on filesystem (basically, `__file__`), so you can do query for `rpmdb_sack` and make relationship between loaded plugins and removal transaction.

**Comment by j-mracek** [comment]
@ignatenkobrain Required version changed to 2.4.2

**Pull request merged**
