### PR TITLE
tracer: don't run tracer when nothing to do; Fix FrostyX/tracer#38

### PR DESCRIPTION
**Pull request by FrostyX**
Please see the FrostyX/tracer#38 for issue description.

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
I think this might be a bug in DNF API.
I think that `transaction()` callback in plugins shouldn't be started in case of `nothing to do`. @rholy @jsilhan ?

**Comment by rholy** [comment]
Hm, hard to tell... I think that some plugins might be interested in the fact that the resolution led to an empty transaction... What do you think @jsilhan ?

**Comment by ignatenkobrain** [comment]
@rholy I think something `demands.run_transaction_if_nothing_to_do = True` can help in this case. because most of plugin don't want this

**Comment by jsilhan** [comment]
I would give plugins opportunity to execute their action even when the transaction is empty. It's better than not having the ability to do what they want.
WRT `demands.run_transaction_if_nothing_to_do = True` - it's one line to one line deal (`if not self.base.transaction: return`) -> IMO it would not make live easier.
I ACK the patch.

**Comment by FrostyX** [comment]
I agree with @jsilhan. In my opinion, it should be up to plugin to decide what to do when transaction is empty. Possibility to do nothing is there and its very clear and obvious. I think that adding some kind of variable determining whether it should be executed or not, will be unnecessarily hacky.

Thank you for merging!

**Pull request merged**
