### PR TITLE
[RFC] initial offline-upgrade plugin

### PR DESCRIPTION
**Pull request by maage**
I reused system_upgrade plugin and removed release version handling and "clean" parts.

Previous exclude stuff might be fixed at https://bugzilla.redhat.com/show_bug.cgi?id=1643551 .

It is very lightly tested and there is some extra code about dbus updates maybe working or not.

This kind of duplicates PackageKit offline update, but I just want to use dnf as one and only package manager.

As it uses same directories and cache as normal dnf, this should not increase filesystem usage. And as it also uses same metadata, you are responsible to refresh metadata as you like it. If you think offline update is not required, you can just call `dnf distro-sync` and do online update and use readily downloaded packages.

https://www.freedesktop.org/software/systemd/man/systemd.offline-updates.html
https://lwn.net/Articles/702629/

If you really want to do offline upgrade I suggest you run this with tracer plugin disabled:
```
dnf offline-upgrade download --disableplugin=tracer -y
```

### CODE REVIEW

**Comment by maage** [comment]
There were some python style issues with my first version. Sorry about that.

**Comment by bochecha** [comment]
Trying to build this, the build system complains:

```
/home/mathieu/dnf-plugins-extras/doc/offline-upgrade.rst:18: WARNING: Title overline too short.

=========================
DNF offline-upgrade Plugin
=========================
```

Seems like a very easy to fix problem. :slightly_smiling_face:

**Comment by bochecha** [comment]
Additionally, the spec file is missing the declarations for the new files:

```
   /usr/lib/python2.7/site-packages/dnf-plugins/offline_upgrade.py
   /usr/lib/python2.7/site-packages/dnf-plugins/offline_upgrade.pyc
   /usr/lib/python2.7/site-packages/dnf-plugins/offline_upgrade.pyo
   /usr/lib/python3.7/site-packages/dnf-plugins/__pycache__/offline_upgrade.cpython-37.opt-1.pyc
   /usr/lib/python3.7/site-packages/dnf-plugins/__pycache__/offline_upgrade.cpython-37.pyc
   /usr/lib/python3.7/site-packages/dnf-plugins/offline_upgrade.py
   /usr/lib/systemd/system/dnf-offline-upgrade-cleanup.service
   /usr/lib/systemd/system/dnf-offline-upgrade.service
   /usr/share/man/man8/dnf.plugin.offline-upgrade.8.gz
```

**Comment by bochecha** [comment]
I just ran update with this plugin on Fedora 29 ARM, and got this:

```
# dnf history info last
Transaction ID : 15
Begin time     : Monday, October 29, 2018 AM01:30:09 CET
Begin rpmdb    : 331:af06d9c0816d86371daeb3ebb6ab92df1c4c71bb
End time       : Monday, October 29, 2018 AM01:30:36 CET (27 seconds)
End rpmdb      : 331:04a50daced134c25ecb11287485aea82f823a1c3
User           : System <unset>
Return-Code    : Success
Releasever     : 29
Command Line   : offline-upgrade upgrade
Packages Altered:
    Upgrade  glibc-2.28-20.fc29.armv7hl             @updates
    Upgraded glibc-2.28-17.fc29.armv7hl             @@System
    Upgrade  glibc-common-2.28-20.fc29.armv7hl      @updates
    Upgraded glibc-common-2.28-17.fc29.armv7hl      @@System
    Upgrade  glibc-langpack-en-2.28-20.fc29.armv7hl @updates
    Upgraded glibc-langpack-en-2.28-17.fc29.armv7hl @@System
Scriptlet output:
   1 warning: Unable to get systemd shutdown inhibition lock: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
```

That warning is a bit worrying, but it seems to have worked just fine. :slightly_smiling_face:

**Comment by j-mracek** [comment]
The code base is similar with system-upgrade plugin therefore probably more generic approach that share code base would be better. I also believe that we should use a different way how to store data for offline operation. Probably using internal Software database would be better. The present implementation is unable to handle new dependencies that are marked as user an installed.

**Comment by maage** [comment]
Yes there is multiple similarities. I've updated my code and changed how to run testsuite. It tries mostlly to test upgrade procedure goes okay when done one operation after another. And then I've added couple of testcases to get better coverage.

**Comment by j-mracek** [comment]
I see a lot of work invested in this PR. The main problem is that this code has a high similarity with system-upgrade command but not the same code base. It means that any issue discovered would require to be fixed on multiple places. It will require more time for maintenance. What about to use a different approach like repolist and repoinfo commands where command aliases are used and behavior is adjusted according to alias used. Another approach would be to use the python inheritance like `repoquery` and `deplist` commands.

**Comment by j-mracek** [comment]
I create an alternative patch https://github.com/rpm-software-management/dnf-plugins-extras/pull/171 that will provide also the offline-upgrade command. I will be happy to hear your opinion.

**Comment by j-mracek** [comment]
Thank you very much for contribution, but an alternative solution was merged into master.

**Comment by maage** [comment]
Thank you!

**Pull request closed without merging**
