### PR TITLE
Change --repoid to --repo in repoclosure documentation

### PR DESCRIPTION
**Pull request by lubomir**
The examples don't match the option description. Let's fix that.

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
IMO we should rename repo to repoid to match yum compatibility.. @jsilhan @j-mracek

**Comment by j-mracek** [comment]
@ignatenkobrain Here is the patch, but I think that it can be undescribed alias in man: https://github.com/rpm-software-management/dnf/pull/720

**Comment by j-mracek** [comment]
@dnf-bot r+

**Comment by j-mracek** [comment]
Thanks for contribution.

**Pull request closed without merging**
