### PR TITLE
Releasever for system-upgrade is now set in pre_configuration()

### PR DESCRIPTION
**Pull request by m-blaha**
Also removing now empty file /system-update/.dnf-system-upgrade

originally was this PR https://github.com/rpm-software-management/dnf-plugins-extras/pull/108 which I accidentally closed.

### CODE REVIEW

**Comment by j-mracek** [comment]
@rh-atomic-bot try

**Comment by j-mracek** [comment]
It will be merged after Fedora27 release.

**Comment by ignatenkobrain** [comment]
@j-mracek how is it related to F27 release? That one is frozen and any updates will go to updates repo anyway..

**Comment by j-mracek** [comment]
Just a plan

**Pull request merged**
