### PR TITLE
leaves: Reuse query instead of constructing fresh one for each package

### PR DESCRIPTION
**Pull request by scop**
Speeds up one run() from ~2.6 seconds to ~1.1 on my system.

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
Thanks, merged.

**Comment by scop** [comment]
@ignatenkobrain When can we expect a new release with this included? The *-leaves plugins could really use this speedup...

**Comment by ignatenkobrain** [comment]
1-2 weeks.

**Comment by scop** [comment]
@ignatenkobrain it's now been about 5 weeks since your "1-2 weeks" comment, ping ;)

**Comment by ignatenkobrain** [comment]
@scop we have a lot of changes in dnf, so I can't just push new tag and build it in fedora =(

**Comment by scop** [comment]
@ignatenkobrain well at least it would be trivial to just take this change and add it as a patch to the Fedora package. You don't even have to do it if you don't feel like it, just let me know and I'll take care of it.

**Comment by ignatenkobrain** [comment]
@scop would be happy if you will do this for me!

**Pull request merged**
